### ISSUE TITLE
Implement instagram authentication

### ISSUE THREAD

**Issue by mgrosen** [ASignificantOtter/ZoleoTracker#2]
Just get auth flow working

### Tasks
- [ ] Create an instagram app
- [ ] implement the sign in flow for getting short-term token
- [ ] exchange short-term token for a long-term token (or is it just another short term token?)

## Exit Criteria
- [ ] Can call an authenticated API as the user
- [ ] unit tests that mock out the instagram/meta dependency to validate that our code handles expected scenarios correctly
