### ISSUE TITLE
Create and host media for posts

### ISSUE THREAD

**Issue by ASignificantOtter** [ASignificantOtter/ZoleoTracker#6]
Need to host/upload whatever media is used for IG posts.

### Tasks ### 

- [ ] Create / use public server for photo media
- [ ] Automate upload of images to server
- [ ] Use google maps api to auto create image based off GPS
